-- The Commonwealth of Yesterday: database definitions (BNW + Vox Populi)
INSERT OR REPLACE INTO Colors (Type, Red, Green, Blue, Alpha) VALUES
('COLOR_COMMONWEALTH_YESTERDAY_PRIMARY', 0.90, 0.43, 0.16, 1),
('COLOR_COMMONWEALTH_YESTERDAY_SECONDARY', 0.12, 0.18, 0.31, 1);
INSERT OR REPLACE INTO PlayerColors (Type, PrimaryColor, SecondaryColor, TextColor) VALUES
('PLAYERCOLOR_COMMONWEALTH_YESTERDAY', 'COLOR_COMMONWEALTH_YESTERDAY_PRIMARY', 'COLOR_COMMONWEALTH_YESTERDAY_SECONDARY', 'COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Traits (Type, Description, ShortDescription) VALUES
('TRAIT_COMMONWEALTH_MEMORIES', 'TXT_KEY_TRAIT_COMMONWEALTH_MEMORIES_HELP', 'TXT_KEY_TRAIT_COMMONWEALTH_MEMORIES_SHORT');

INSERT INTO Leaders
(Type, Description, Civilopedia, CivilopediaTag, ArtDefineTag, PrimaryVictoryPursuit, SecondaryVictoryPursuit,
 VictoryCompetitiveness, WonderCompetitiveness, MinorCivCompetitiveness, Boldness, DiploBalance, WarmongerHate,
 DoFWillingness, DenounceWillingness, WorkWithWillingness, WorkAgainstWillingness, Loyalty, Forgiveness,
 Neediness, Meanness, Chattiness, PortraitIndex, IconAtlas)
SELECT 'LEADER_CHILD_WE_WERE', 'TXT_KEY_LEADER_CHILD_WE_WERE', 'TXT_KEY_LEADER_CHILD_WE_WERE_PEDIA',
 'TXT_KEY_CIVILOPEDIA_LEADERS_CHILD_WE_WERE', ArtDefineTag, 'VICTORY_PURSUIT_CULTURE', 'VICTORY_PURSUIT_DIPLOMACY',
 5, 7, 6, 4, 7, 7, 9, 4, 9, 3, 9, 8, 5, 3, 7, PortraitIndex, IconAtlas
FROM Leaders WHERE Type = 'LEADER_WASHINGTON';
INSERT INTO Leader_Traits VALUES ('LEADER_CHILD_WE_WERE', 'TRAIT_COMMONWEALTH_MEMORIES');
INSERT INTO Leader_MajorCivApproachBiases SELECT 'LEADER_CHILD_WE_WERE', MajorCivApproachType, Bias FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_GANDHI';
INSERT INTO Leader_MinorCivApproachBiases SELECT 'LEADER_CHILD_WE_WERE', MinorCivApproachType, Bias FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_GANDHI';
INSERT INTO Leader_Flavors SELECT 'LEADER_CHILD_WE_WERE', FlavorType, Flavor FROM Leader_Flavors WHERE LeaderType='LEADER_GANDHI';
UPDATE Leader_Flavors SET Flavor=10 WHERE LeaderType='LEADER_CHILD_WE_WERE' AND FlavorType IN ('FLAVOR_CULTURE','FLAVOR_GREAT_PEOPLE');

INSERT INTO Civilizations
(Type, Description, Civilopedia, CivilopediaTag, Strategy, Playable, AIPlayable, ShortDescription, Adjective,
 DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, PortraitIndex, IconAtlas,
 AlphaIconAtlas, MapImage, DawnOfManQuote, DawnOfManImage, DawnOfManAudio, SoundtrackTag)
SELECT 'CIVILIZATION_COMMONWEALTH_YESTERDAY', 'TXT_KEY_CIV_COMMONWEALTH_DESC', 'TXT_KEY_CIV_COMMONWEALTH_PEDIA',
 'TXT_KEY_CIV5_COMMONWEALTH', 'TXT_KEY_CIV_COMMONWEALTH_STRATEGY', 1, 1, 'TXT_KEY_CIV_COMMONWEALTH_SHORT_DESC',
 'TXT_KEY_CIV_COMMONWEALTH_ADJECTIVE', 'PLAYERCOLOR_COMMONWEALTH_YESTERDAY', ArtDefineTag, ArtStyleType,
 ArtStyleSuffix, ArtStylePrefix, PortraitIndex, IconAtlas, AlphaIconAtlas, MapImage,
 'TXT_KEY_CIV5_DOM_COMMONWEALTH_TEXT', 'Art/DawnOfMan/CommonwealthDawnOfMan.dds', DawnOfManAudio, SoundtrackTag
FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','LEADER_CHILD_WE_WERE');
INSERT INTO Civilization_FreeBuildingClasses VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','TECH_AGRICULTURE');
-- The handicap supplies the normal starting defender, which resolves through
-- the Warrior override as one Old Friend. Adding a Warrior here would create a
-- duplicate, so the civilization only declares its Settler like base-game civs.
INSERT INTO Civilization_FreeUnits (CivilizationType, UnitClassType, UnitAIType, Count) VALUES
('CIVILIZATION_COMMONWEALTH_YESTERDAY','UNITCLASS_SETTLER','UNITAI_SETTLE',1);
INSERT INTO Civilization_Start_Region_Priority VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','REGION_GRASS');
INSERT INTO Civilization_CityNames VALUES
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_HOME'),
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_NEW_HOME'),
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_OLD_SERVER'),
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_SUMMER_END'),
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_AFTER_SCHOOL'),
('CIVILIZATION_COMMONWEALTH_YESTERDAY','TXT_KEY_CITY_LAST_LIGHT');

-- Old Friend: Warrior replacement retaining its identity through upgrades.
INSERT INTO Units
(Type, Description, Civilopedia, Strategy, Help, Combat, Cost, FaithCost, RequiresFaithPurchaseEnabled, Moves,
 BaseSightRange, Class, CombatClass, Domain, DefaultUnitAI, MilitarySupport, MilitaryProduction, Pillage,
 PrereqTech, ObsoleteTech, GoodyHutUpgradeUnitClass, HurryCostModifier, ExtraMaintenanceCost, UnitArtInfo,
 UnitArtInfoCulturalVariation, UnitArtInfoEraVariation, UnitFlagIconOffset, PortraitIndex, IconAtlas,
 UnitFlagAtlas, ShowInPedia)
SELECT 'UNIT_COMMONWEALTH_OLD_FRIEND','TXT_KEY_UNIT_OLD_FRIEND','TXT_KEY_UNIT_OLD_FRIEND_PEDIA',
 'TXT_KEY_UNIT_OLD_FRIEND_STRATEGY','TXT_KEY_UNIT_OLD_FRIEND_HELP',Combat,40,FaithCost,
 RequiresFaithPurchaseEnabled,Moves,BaseSightRange,Class,CombatClass,Domain,DefaultUnitAI,MilitarySupport,
 MilitaryProduction,Pillage,PrereqTech,ObsoleteTech,GoodyHutUpgradeUnitClass,HurryCostModifier,
 ExtraMaintenanceCost,UnitArtInfo,UnitArtInfoCulturalVariation,UnitArtInfoEraVariation,UnitFlagIconOffset,
 PortraitIndex,IconAtlas,UnitFlagAtlas,1 FROM Units WHERE Type='UNIT_WARRIOR';
INSERT INTO Unit_AITypes SELECT 'UNIT_COMMONWEALTH_OLD_FRIEND', UnitAIType FROM Unit_AITypes WHERE UnitType='UNIT_WARRIOR';
INSERT INTO Unit_Flavors SELECT 'UNIT_COMMONWEALTH_OLD_FRIEND', FlavorType, Flavor FROM Unit_Flavors WHERE UnitType='UNIT_WARRIOR';

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,CombatPercent,PortraitIndex,IconAtlas,PediaType,PediaEntry,ShowInUnitPanel)
VALUES
('PROMOTION_COMMONWEALTH_SINCE_BEGINNING','TXT_KEY_PROMOTION_SINCE_BEGINNING','TXT_KEY_PROMOTION_SINCE_BEGINNING_HELP',1,0,0,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_SINCE_BEGINNING',1),
('PROMOTION_COMMONWEALTH_ADJACENT_FRIEND','TXT_KEY_PROMOTION_BOYS_STILL_HERE','TXT_KEY_PROMOTION_BOYS_STILL_HERE_HELP',1,0,10,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_BOYS_STILL_HERE',0),
('PROMOTION_COMMONWEALTH_REMINISCENCE_ADJ','TXT_KEY_REMINISCENCE_BOYS','TXT_KEY_REMINISCENCE_BOYS_HELP',1,0,10,58,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_REMINISCENCE_BOYS',0),
('PROMOTION_COMMONWEALTH_YEARS_1','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,2,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',0),
('PROMOTION_COMMONWEALTH_YEARS_2','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,4,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',0),
('PROMOTION_COMMONWEALTH_YEARS_3','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,6,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',0),
('PROMOTION_COMMONWEALTH_YEARS_4','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,8,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',0),
('PROMOTION_COMMONWEALTH_YEARS_5','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,10,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',0),
('PROMOTION_COMMONWEALTH_YEARS_6','TXT_KEY_PROMOTION_YEARS','TXT_KEY_PROMOTION_YEARS_HELP',1,0,12,59,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_PROMOTION_YEARS',1),
('PROMOTION_COMMONWEALTH_WORKER_MOVE','TXT_KEY_REMINISCENCE_WORLD','TXT_KEY_REMINISCENCE_WORLD_HELP',1,1,0,58,'ABILITY_ATLAS','PEDIA_SHARED','TXT_KEY_REMINISCENCE_WORLD',0);
UPDATE UnitPromotions SET MovesChange=1, WorkRateMod=25 WHERE Type='PROMOTION_COMMONWEALTH_WORKER_MOVE';
INSERT INTO Unit_FreePromotions VALUES ('UNIT_COMMONWEALTH_OLD_FRIEND','PROMOTION_COMMONWEALTH_SINCE_BEGINNING');
INSERT INTO Civilization_UnitClassOverrides VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','UNITCLASS_WARRIOR','UNIT_COMMONWEALTH_OLD_FRIEND');

-- Childhood Bedroom and invisible per-city state buildings.
INSERT INTO Buildings
(Type,Description,Civilopedia,Strategy,Help,GoldMaintenance,Cost,FaithCost,HurryCostModifier,MinAreaSize,
 ConquestProb,Happiness,UnmoddedHappiness,BuildingClass,ArtDefineTag,PrereqTech,FreeStartEra,PortraitIndex,
 IconAtlas,ArtInfoCulturalVariation,ArtInfoEraVariation,ArtInfoRandomVariation,ShowInPedia)
SELECT 'BUILDING_COMMONWEALTH_BEDROOM','TXT_KEY_BUILDING_BEDROOM','TXT_KEY_BUILDING_BEDROOM_PEDIA',
 'TXT_KEY_BUILDING_BEDROOM_STRATEGY','TXT_KEY_BUILDING_BEDROOM_HELP',0,40,FaithCost,HurryCostModifier,
 MinAreaSize,ConquestProb,1,0,BuildingClass,ArtDefineTag,NULL,FreeStartEra,PortraitIndex,IconAtlas,
 ArtInfoCulturalVariation,ArtInfoEraVariation,ArtInfoRandomVariation,1
FROM Buildings WHERE Type='BUILDING_MONUMENT';
INSERT INTO Building_YieldChanges VALUES ('BUILDING_COMMONWEALTH_BEDROOM','YIELD_CULTURE',2);
INSERT INTO Building_Flavors SELECT 'BUILDING_COMMONWEALTH_BEDROOM',FlavorType,Flavor FROM Building_Flavors WHERE BuildingType='BUILDING_MONUMENT';
INSERT INTO Civilization_BuildingClassOverrides VALUES ('CIVILIZATION_COMMONWEALTH_YESTERDAY','BUILDINGCLASS_MONUMENT','BUILDING_COMMONWEALTH_BEDROOM');

INSERT INTO BuildingClasses (Type,DefaultBuilding,Description,MaxGlobalInstances,MaxTeamInstances,MaxPlayerInstances) VALUES
('BUILDINGCLASS_COMMONWEALTH_KEEP_1','BUILDING_COMMONWEALTH_KEEP_1','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_KEEP_2','BUILDING_COMMONWEALTH_KEEP_2','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_KEEP_3','BUILDING_COMMONWEALTH_KEEP_3','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_KEEP_4','BUILDING_COMMONWEALTH_KEEP_4','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_PRODUCTION','BUILDING_COMMONWEALTH_PRODUCTION','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_CULTURE','BUILDING_COMMONWEALTH_CULTURE','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_SCIENCE','BUILDING_COMMONWEALTH_SCIENCE','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_HAPPINESS','BUILDING_COMMONWEALTH_HAPPINESS','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1),
('BUILDINGCLASS_COMMONWEALTH_BEDROOM_FOOD','BUILDING_COMMONWEALTH_BEDROOM_FOOD','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,-1);
INSERT INTO Buildings (Type,BuildingClass,Description,Cost,FaithCost,PrereqTech,NeverCapture,NukeImmune,ConquestProb,GreatWorkCount,IconAtlas,PortraitIndex,ShowInPedia) VALUES
('BUILDING_COMMONWEALTH_KEEP_1','BUILDINGCLASS_COMMONWEALTH_KEEP_1','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_KEEP_2','BUILDINGCLASS_COMMONWEALTH_KEEP_2','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_KEEP_3','BUILDINGCLASS_COMMONWEALTH_KEEP_3','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_KEEP_4','BUILDINGCLASS_COMMONWEALTH_KEEP_4','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_PRODUCTION','BUILDINGCLASS_COMMONWEALTH_PRODUCTION','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_CULTURE','BUILDINGCLASS_COMMONWEALTH_CULTURE','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_SCIENCE','BUILDINGCLASS_COMMONWEALTH_SCIENCE','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_HAPPINESS','BUILDINGCLASS_COMMONWEALTH_HAPPINESS','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0),
('BUILDING_COMMONWEALTH_BEDROOM_FOOD','BUILDINGCLASS_COMMONWEALTH_BEDROOM_FOOD','TXT_KEY_BUILDING_KEEPSAKE',-1,-1,NULL,1,1,0,-1,'BUILDING_ATLAS',0,0);
INSERT INTO Building_YieldChanges VALUES
('BUILDING_COMMONWEALTH_KEEP_1','YIELD_CULTURE',1),('BUILDING_COMMONWEALTH_KEEP_2','YIELD_CULTURE',1),
('BUILDING_COMMONWEALTH_KEEP_3','YIELD_CULTURE',1),('BUILDING_COMMONWEALTH_KEEP_4','YIELD_CULTURE',1);

-- Reused by Lua with per-city counts. Each copy is one percentage point.
INSERT INTO Building_YieldModifiers VALUES
('BUILDING_COMMONWEALTH_PRODUCTION','YIELD_PRODUCTION',1),
('BUILDING_COMMONWEALTH_CULTURE','YIELD_CULTURE',1),
('BUILDING_COMMONWEALTH_SCIENCE','YIELD_SCIENCE',1);
INSERT INTO Building_YieldChanges VALUES ('BUILDING_COMMONWEALTH_BEDROOM_FOOD','YIELD_FOOD',1);
UPDATE Buildings SET Happiness=1 WHERE Type='BUILDING_COMMONWEALTH_HAPPINESS';
