INSERT OR REPLACE INTO Language_en_US (Tag,Text) VALUES
('TXT_KEY_CIV_COMMONWEALTH_DESC','The Commonwealth of Yesterday'),
('TXT_KEY_CIV_COMMONWEALTH_SHORT_DESC','The Commonwealth of Yesterday'),
('TXT_KEY_CIV_COMMONWEALTH_ADJECTIVE','Nostalgic'),
('TXT_KEY_LEADER_CHILD_WE_WERE','The Child We Were'),
('TXT_KEY_LEADER_CHILD_WE_WERE_PEDIA','The child who remembers when every night belonged to the group.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_CHILD_WE_WERE','The Child We Were'),
('TXT_KEY_CIV_COMMONWEALTH_PEDIA','A commonwealth built from old worlds, old names, and friendships carried forward.'),
('TXT_KEY_CIV5_COMMONWEALTH','The Commonwealth of Yesterday'),
('TXT_KEY_CIV_COMMONWEALTH_STRATEGY','Preserve Old Friends and build Childhood Bedrooms early. Spend Memories on Reminiscences at decisive moments, then prepare for Melancholy.'),
('TXT_KEY_TRAIT_COMMONWEALTH_MEMORIES_SHORT','We Didn''t Know We Were Making Memories'),
('TXT_KEY_TRAIT_COMMONWEALTH_MEMORIES_HELP','Progress creates [COLOR_POSITIVE_TEXT]Memories[ENDCOLOR] that can temporarily relive a simpler time. Old Friends and Childhood Bedrooms become more valuable as they survive across eras.'),
('TXT_KEY_CIV5_DOM_COMMONWEALTH_TEXT','There was a time, beloved child, when the night seemed endless. Your friends did not disappear; life simply became busier. Now carry every fragment of the past forward, and build something worthy of remembering.'),
('TXT_KEY_CITY_HOME','Home'),('TXT_KEY_CITY_NEW_HOME','New Home'),('TXT_KEY_CITY_OLD_SERVER','The Old Server'),
('TXT_KEY_CITY_SUMMER_END','Summer''s End'),('TXT_KEY_CITY_AFTER_SCHOOL','After School'),('TXT_KEY_CITY_LAST_LIGHT','Last Light'),
('TXT_KEY_UNIT_OLD_FRIEND','Old Friend'),
('TXT_KEY_UNIT_OLD_FRIEND_PEDIA','Not a disposable warrior, but one of the people who was there when the world was new.'),
('TXT_KEY_UNIT_OLD_FRIEND_STRATEGY','Keep Old Friends alive and near one another. They gain strength whenever the civilization enters a new era.'),
('TXT_KEY_UNIT_OLD_FRIEND_HELP','Replaces the Warrior. Retains [COLOR_POSITIVE_TEXT]Since the Beginning[ENDCOLOR] through upgrades, gains up to +12% Strength across eras, and fights better beside another Old Friend.'),
('TXT_KEY_PROMOTION_SINCE_BEGINNING','Since the Beginning'),
('TXT_KEY_PROMOTION_SINCE_BEGINNING_HELP','Retained through upgrades. Gains Years Together, healing, and Memories at each era transition.'),
('TXT_KEY_PROMOTION_BOYS_STILL_HERE','The Boys Are Still Here'),
('TXT_KEY_PROMOTION_BOYS_STILL_HERE_HELP','[COLOR_POSITIVE_TEXT]+10% Combat Strength[ENDCOLOR] while adjacent to another Old Friend.'),
('TXT_KEY_PROMOTION_YEARS','Years Together'),('TXT_KEY_PROMOTION_YEARS_HELP','Up to [COLOR_POSITIVE_TEXT]+12% Combat Strength[ENDCOLOR] from surviving era transitions.'),
('TXT_KEY_REMINISCENCE_BOYS','The Boys Are Online'),('TXT_KEY_REMINISCENCE_BOYS_HELP','Temporary combat bonus while adjacent to a friendly military unit.'),
('TXT_KEY_REMINISCENCE_WORLD','One More World Before Bed'),('TXT_KEY_REMINISCENCE_WORLD_HELP','Temporary +1 Movement and +25% work rate for Workers.'),
('TXT_KEY_BUILDING_BEDROOM','Childhood Bedroom'),
('TXT_KEY_BUILDING_BEDROOM_PEDIA','The room remains while the person who lived there grows older.'),
('TXT_KEY_BUILDING_BEDROOM_STRATEGY','Build early. It gains one Keepsake at each later era transition, up to four.'),
('TXT_KEY_BUILDING_BEDROOM_HELP','Replaces the Monument. +2 Culture and +1 Local Happiness. Gains up to four Keepsakes across eras; each adds +1 Culture and every two add +1 Tourism after Archaeology.'),
('TXT_KEY_BUILDING_KEEPSAKE','Keepsake');
